### ISSUE TITLE
console error running locally

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/rise-rss#25]
When trying to use rise rss component in my project i get the following console error and the data is not returned as expected: http://www.screencast.com/t/ZUMtdPa3D

REPRODCUTION STEPS:
I followed the usage instructions and brought the dependency into my project with bower. Then I constructed the html like in the example making sure to link to webcomponents-lite.min.js and rise-rss.html. Lastly I changed the  url attribute to my rss feed.
url="https://sports.yahoo.com/nfl/rss.xml"

EXPECTED RESULTS
I was then expecting to see the data returned in json format in the console but instead got an error.

RESULTS
I get the following errors in console
http://www.screencast.com/t/ZUMtdPa3D

**Comment by sumedh-coditas** [comment]
Getting the same error...

**Comment by rudibravo** [comment]
I couldn't reproduce this issue. I see the errors but the json is also present.
